### ISSUE TITLE
Start using RPC Signer in production

### ISSUE THREAD

**Issue by electricmonk** [orbs-network/orbs-network-go#1189]
- [ ] Use gRPC instead of plain HTTP
- [ ] Get to run on production-like testnet
- [ ] Upgrade Boyar in production
- [ ] Set config so that mainnet uses RPC signer
- [ ] V2 spec with @OdedWx

**Comment by noambergIL** [comment]
@OdedWx @electricmonk, currently the vault implements proto that is for membuf and contain some non-standard fields (as far as i understand) then it is part of the services package and then both crypto and http-server ... in order to make it grpc as far as i see the "service" needs to be a "clean" proto so it can compile to a standard grpc server. on top of that we could in theory plug the membuf ... 
i need a bit of guidance here
