### ISSUE TITLE
Make sure build process identifies requirements for contracts deployments own go.mod

### ISSUE THREAD

**Issue by itamararjuan** [orbs-network/orbs-network-go#1334]
Our contracts use a whitelist of packages allowed for importing, these imports which are non core in Golang are covered by a unique and reserved go.mod file for the purpose of contracts compliations inside the `native-src` folder of the node running the Orbs binary.

At the moment of opening this issue - there is a dedicated static file which is used while building the docker image for the Orbs node. if a module which both the binary and our contract compliations both need - that dependency needs to be aligned.

At the moment if one of the people working on the core project updates the go.mod of the main project to use let's say a different version of `orbs-contract-sdk` then contract compliatinos would break since the versions will mismatch

We need to find a way to auto-generate the go.mod which is shipped with the docker image of Orbs which is used inside `native-src` and NOT rely on a static file which includes hard coded versions of depedencies and is error prone.

**Comment by electricmonk** [comment]
@itamararjuan please handle ASAP

**Comment by netoneko** [comment]
The `go.mod` file that we use to ship with Docker should be part of the main binary. The current system is contradictory: 

* we allow to set the processor artifacts path in the config
* we assume that `go.mod` is in the default location of `/src/_tmp/processor-artifacts/`.
* if you deviate from this assumed path, the compilation just won't work because it will miss the `go.mod`

It means that our binaries will not work outside of Docker.

If we add a separate step of building assets that we include in the main binary, we could avoid this problem, because then during the asset compilation step we could generate an appropriate `go.mod` however we like.

I have an example of the process here: https://github.com/orbs-network/orbs-network-javascript-plugin/blob/52071fc60e439222ae758f4af8e8e67e1e9bb3ac/build-binaries.sh#L9

**Comment by electricmonk** [comment]
do we actually need to allow setting the artifact path? if we always use `os.TempDir`, wouldn't that solve the problem inherently? all we'll need to do is make sure that the processor copies `go.mod` to that dir as part of its init logic

**Comment by netoneko** [comment]
Fixed in #1557
