### ISSUE TITLE
Experimental libraries are missing from experimental build

### ISSUE THREAD

**Issue by netoneko** [orbs-network/orbs-network-go#1507]
<img width="1440" alt="Screen Shot 2019-12-17 at 23 14 49" src="https://user-images.githubusercontent.com/614125/71034935-236adf80-2123-11ea-89b9-bd5eec8069c2.png">

**Comment by electricmonk** [comment]
@itamararjuan can you please take a look? I think that this got fucked up in the latest CI refactor.
For some reason we have conditional logic for the experimental build both in `build-docker-node.sh` and `build-binaries-in-superfluous-container.sh` (which runs inside the build container), and we set `ORBS_EXPERIMENTAL` from `CIRCLE_TAG` in the container. 

I think there should be a single place of decision.

What happens is that the E2E doesn't run since `ORBS_EXPERIMENTAL` is not set - which defeats the purpose of having this test. Maybe the test should check the `CIRCLE_TAG` variable?
