### ISSUE TITLE
Change transport interface to use a reader/writer interface instead of slice

### ISSUE THREAD

**Issue by jlevison** [orbs-network/orbs-network-go#159]
its not trivial, this issue is missing the guidance into what the new api will look like as its a complex case to solve - to be updated in the future

**Comment by talkol** [comment]
not sure anymore we should still do it

there's a queue for outgoing sends since multiple sends for one peer can be started concurrently from different goroutines

the queue is basically a channel, but the reader/writer interface doesn't play with this nicely

right now we have byte buffers and it's very easy to store these pointers to byte buffers in the channel itself

**Comment by electricmonk** [comment]
I think that when we have huge blocks (1MB in size), we might want to reconsider, if we see that they hog the GC - in which case, we'll want to hold blocks as chunked slices rather than consecutive bytes, which will require use to move to a Reader/Writer interface

**Comment by electricmonk** [comment]
Closing for now, if we feel there's a real problem when there's actual traffic, we'll reconsider
