### ISSUE TITLE
Acceptance test failed in CI on out of memory

### ISSUE THREAD

**Issue by electricmonk** [orbs-network/orbs-network-go#240]
https://circleci.com/gh/orbs-network/orbs-network-go/1164

**Comment by talkol** [comment]
## According to pprof (memory profiler):
`go test -memprofile mem.prof ./test/acceptance -count 10`
`go tool pprof mem.prof`

### Results:
```
      flat  flat%   sum%        cum   cum%
  293.32MB 88.37% 88.37%   293.32MB 88.37%  github.com/orbs-network/orbs-network-go/services/statestorage/merkle.(*Node).clone
       8MB  2.41% 90.79%        8MB  2.41%  github.com/orbs-network/orbs-network-go/vendor/github.com/orbs-network/membuffers/go.(*InternalMessage).lazyCalcOffsets
    4.02MB  1.21% 92.00%     4.02MB  1.21%  github.com/orbs-network/orbs-network-go/services/statestorage/merkle.createNode (inline)
    3.01MB  0.91% 92.90%     3.01MB  0.91%  github.com/orbs-network/orbs-network-go/test/harness/services/blockstorage/adapter.(*inMemoryBlockPersistence).getChanFor (inline)
    2.50MB  0.75% 93.66%     2.50MB  0.75%  github.com/orbs-network/orbs-network-go/services/statestorage/adapter.(*InMemoryStatePersistence).cloneCurrentStateDiff
       2MB   0.6% 94.26%        2MB   0.6%  github.com/orbs-network/orbs-network-go/crypto/hash.CalcSha256
       2MB   0.6% 94.86%        2MB   0.6%  github.com/orbs-network/orbs-network-go/vendor/github.com/orbs-network/orbs-spec/types/go/primitives.primitives.MerkleSha256.KeyForMap (inline)
    1.54MB  0.46% 95.33%   301.88MB 90.95%  github.com/orbs-network/orbs-network-go/services/statestorage/merkle.(*Forest).updateSingleEntry
    1.50MB  0.45% 95.78%        8MB  2.41%  github.com/orbs-network/orbs-network-go/services/gossip.decodeBlockPairs
    0.50MB  0.15% 95.93%        7MB  2.11%  github.com/orbs-network/orbs-network-go/services/statestorage/adapter.(*InMemoryStatePersistence).WriteState
    0.50MB  0.15% 96.08%        3MB   0.9%  github.com/orbs-network/orbs-network-go/services/consensuscontext.(*service).createResultsBlock
         0     0% 96.08%   314.90MB 94.88%  github.com/orbs-network/orbs-network-go/services/blockstorage.(*service).CommitBlock
         0     0% 96.08%   310.89MB 93.67%  github.com/orbs-network/orbs-network-go/services/blockstorage.(*service).syncBlockToStateStorage
         0     0% 96.08%   221.83MB 66.84%  github.com/orbs-network/orbs-network-go/services/consensusalgo/benchmarkconsensus.(*service).HandleBenchmarkConsensusCommit
         0     0% 96.08%    99.06MB 29.85%  github.com/orbs-network/orbs-network-go/services/consensusalgo/benchmarkconsensus.(*service).leaderConsensusRoundRunLoop
         0     0% 96.08%    99.06MB 29.85%  github.com/orbs-network/orbs-network-go/services/consensusalgo/benchmarkconsensus.(*service).leaderConsensusRoundTick
         0     0% 96.08%        5MB  1.51%  github.com/orbs-network/orbs-network-go/services/consensusalgo/benchmarkconsensus.(*service).leaderGenerateNewProposedBlockUnderMutex
         0     0% 96.08%   221.33MB 66.69%  github.com/orbs-network/orbs-network-go/services/consensusalgo/benchmarkconsensus.(*service).nonLeaderCommitAndReplyUnderMutex
         0     0% 96.08%   221.83MB 66.84%  github.com/orbs-network/orbs-network-go/services/consensusalgo/benchmarkconsensus.(*service).nonLeaderHandleCommit
         0     0% 96.08%   314.90MB 94.88%  github.com/orbs-network/orbs-network-go/services/consensusalgo/benchmarkconsensus.(*service).saveToBlockStorage
```

**Comment by talkol** [comment]
## Looking into the top result:

```
ROUTINE ======================== github.com/orbs-network/orbs-network-go/services/statestorage/merkle.(*Node).clone in /Users/talkol/go/src/github.com/orbs-network/orbs-network-go/services/statestorage/merkle/merkle_forest.go
  293.32MB   293.32MB (flat, cum) 88.37% of Total
         .          .     44:	newBranches := [trieRadix]primitives.MerkleSha256{}
         .          .     45:	copy(newBranches[:], n.branches[:])
         .          .     46:	result := &Node{
         .          .     47:		path:     n.path,
         .          .     48:		value:    n.value, // TODO - copy?
  293.32MB   293.32MB     49:		branches: newBranches,
         .          .     50:	}
         .          .     51:	for k, v := range n.branches {
         .          .     52:		result.branches[k] = v // TODO - copy?
         .          .     53:	}
         .          .     54:	return result
```

**Comment by talkol** [comment]
This is a snapshot in the middle of the stress acceptance test, as you can see there are about 300MB allocated for Merkle stuff

**Comment by talkol** [comment]
The `statestorage` service will eventually become very memory-intensive since it is should ideally hold the entire state snapshot of the virtual chain in-memory.

#### How big is the state?

Let's assume the only usage of the state is to hold token balances (this is one of the main use cases). The key size is 20 bytes (if we use RIPEMD160) or 32 bytes (if we use SHA256). Let's assume 20 bytes. If each balance is uint64 (is this accurate enough? or do we need bigger ints?), then it's 8 bytes for data. Meaning every account is ~30 bytes of memory. If we have 1 million accounts, we consume at least 30MB of memory. If we have 1 billion accounts, we consume at least 30GB of memory.

Since state is held inside a merkle tree, each non-leaf node has its key (20 bytes) and hash (is this 32 bytes?). Which means about 60 bytes per non-leaf node. We have the same number of non-leaf nodes as leaf nodes in a complete binary tree - meaning we need to duplicate our memory consumption x 3 (90MB for 1 million accounts, 90GB for 1 billion accounts).

It shouldn't be difficult to make an exact calculation if we know each of the numbers.

#### What is our memory budget?

Assuming we want to hold 100 million accounts, we can calculate how much memory we must consume according to the above - let's say 9GB of memory.

Since we hold n blocks history (n=5 for example) and we have some overhead, let's say that our memory budget for 100 million accounts is 110% of the minimum. This would be 10GB in our case.

#### Writing a test to check of the budget

We should write a test that will store 10,000 accounts and check the total actual memory consumption. 10,000 accounts should be 900KB and with the 10% overhead - that's 1MB of memory.

Checking the actual memory consumption is possible with the memory profilers. One option is with `runtime/pprof/WriteHeapProfile`, another option is with `runtime/ReadMemStats`.

We should fail the test if we consume more memory than 1MB for these 10,000 accounts.
