### ISSUE TITLE
Decide on error reporting strategy

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-network-go#26]
Consider this for example:

```go
if blockPair.TransactionsBlock.Header == nil {
    return nil, &ErrCodecEncode{"BlockPair", blockPair}
}
```

How do we want to report errors in the system in general?

Some error conditions - like a transaction was rejected because it's expired, need to be passed programmatically though the system until they reach the user so they need a representation that is not string only

**Comment by jlevison** [comment]
I am having a bit of a problem getting the context for the example, but the question is clear: 
* Sentinel errors which are flow / conditions / debugging-aids: reported as a regular error (fmt.Errorf() or errors.New() or any other way of creating an error) - these kind of errors are never really 'handled' as there is a direct flow of what needs to happen, and at the lowest level they will be logged (and the logger will format them)
remember that if you handle an error, its no longer an error.. but perhaps just a debugging log message (equivalent)

* Behavior changing errors - like transaction rejected, will need to be a typed error, they are part of our API and define on how we need to later behave based on the exact error data, so for a transaction that was rejected, it may be because the signature is invalid (never retry) or some timing issue (retry? never retry?) or unknow error? (retry) and so on - there will be a TransactionFailed object that is implementing Error() but also have some more data in its struct so we can work with it.

**Comment by jlevison** [comment]
and to add on that, errors package is useful in cases where you get an error and you want to add your own context to it without messing up the stack:
so this:
`
func fn() *int, error {
        x, err := bar.Foo()
        if err != nil {
                return nil, err
        }
        return x, nil
}
`
can actually be this:
`
func fn() *int, error {
        return bar.Foo()
}
`
but if fn() has some special meaning, such as readNumber(), so maybe we want to give context
`
func fn() *int, error {
        x, err := bar.Foo()
        if err != nil {
                return nil, fmt.Errorf("read number failed: %s", err)
        }
        return x, nil
}
`
but now we messed up the stack trace, we do not know what happened inside Foo() other then the error message
this will keep the context
`
func fn() *int, error {
        x, err := bar.Foo()
        if err != nil {
                return nil, errors.Wrap(err, "read number failed")
        }
        return x, nil
}
`
for anyone consuming the error object in the future, its error.Error() looks normal, but the errors package lets us observe the stack trace and the original error in other ways (which the logger will implement) - not sure yet if we should *always* use errors.New() or its okay to mix and just use the Wrap when needed and fmt.Errorf() in other cases.

All of this is about sentinel errors, not API responses which represent errors or complex flows where errors define behavior

**Comment by talkol** [comment]
This is the context of the example, I don't like what I did here and looking for a better solution:

https://github.com/orbs-network/orbs-network-go/blob/7085153ad4fbe213d36b70f0611b5a0ea21312a2/services/gossip/codec.go#L21

**Comment by talkol** [comment]
We have made the following decisions:

1. We are using this package `errors`: https://golang.org/pkg/errors/

2. Prefer to have simple string errors with `errors.New()` or `errors.Errorf()`

3. If you already have an error in hand (from another API), wrap it with `errors.Wrap` and add you message

4. The test in the error message should start with a lower case

5. If you must have a programatic error return code (for example for returning in PublicApi to clients) - it's ok to create your error object with the name like `ErrTransactionRejected` placed in an `errors.go` file in your service (look for existing examples)
