### ISSUE TITLE
Flakiness in TestBenchmarkConsensusLeaderGetsVotesBeforeNextBlock

### ISSUE THREAD

**Issue by electricmonk** [orbs-network/orbs-network-go#285]
https://circleci.com/gh/orbs-network/orbs-network-go/1471

**Comment by talkol** [comment]
This is the code of the test:

```
		committedTamper := network.GossipTransport().Fail(adapter.BenchmarkConsensusMessage(consensus.BENCHMARK_CONSENSUS_COMMITTED))
		committedLatch := network.GossipTransport().LatchOn(adapter.BenchmarkConsensusMessage(consensus.BENCHMARK_CONSENSUS_COMMITTED))

		network.SendTransferInBackground(ctx, 0, 0, 5, 6) // send a transaction so that network advances to block 1. the tamper prevents COMMITTED messages from reaching leader, so it doesn't move to block 2
		committedLatch.Wait()                             // wait for validator to try acknowledge that it reached block 1 (and fail)
		committedLatch.Wait()                             // wait for another consensus round (to make sure transaction(0) does not arrive after transaction(17) due to scheduling flakiness

		txHash := network.SendTransferInBackground(ctx, 0, 17, 5, 6) // this should be included in block 2 which will not be closed until leader knows network is at block 2

		committedLatch.Wait()

		require.EqualValues(t, 0, <-network.CallGetBalance(ctx, 0, 6), "initial getBalance result on leader")
```

We fail on the last line.

This doesn't make a lot of sense because we only do the transfer after the `GossipTransport().Fail` takes place. The latch is blocking the gossip messages so there's no way consensus could go forward.

The only reason I can think that consensus goes forward is if there's another way to get the commit.. something like block sync maybe?

What if the consensus is frozen but block sync synchronizes the nodes anyways, so the test fails.

My recommendation is to also fail block sync messages in the latch in this test to make sure that block sync isn't active

**Comment by electricmonk** [comment]
I agree, block sync should be operating during the consensus acceptance tests as a general rule
Failing the gossip messages is probably good enough trick

**Comment by talkol** [comment]
My idea was mistaken, we currently suspect it's a different issue (which @netoneko resolved):
https://github.com/orbs-network/orbs-network-go/issues/356
