### ISSUE TITLE
Replace MutableConfig with a struct that can be deserialized from json config file

### ISSUE THREAD

**Issue by electricmonk** [orbs-network/orbs-network-go#498]
There's no real reason, really, to represent the config system as a map. Rather, attempt to unmarshal a json file into a simple struct, failing on unknown fields (this is good! will help detect problems in the config file). This will make it slightly easier to work with the config system in the tests (as fields will have concrete types rather than be keys in a map), but will make merging hard-coded config and config from files a bit harder - I think it's worth-while.

**Comment by netoneko** [comment]
It's easy enough to initialize a map properly, including custom checks applied to each field according to perceived type, rather than shoehorning JSON into struct.

And it's easier to test, too, because JSON serialization in golang is weird, requires a lot of dancing around with struct annotations, does not support pointers, etc.

I don't believe it's worth the effort at all.

Also, consider that merging two configs would be a nightmare in case of structs, and in case of map it simply overwrites existing keys.
