### ISSUE TITLE
Make genesis blocks handling uniform across all services

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-network-go#582]
According to the spec, we don't have a genesis block (it should be nil) and effectively the first block in the system is block 1 (not 0)

We need to sort this out across the system since each service handles this differently

**Comment by electricmonk** [comment]
@OdedWx is this still an issue?

**Comment by OdedWx** [comment]
The genesis block (0) is address by every service, services behaviour was aligned to handle 0 independently without assumptions on other services readiness, with the exception of the ConsensusAlgo waiting for the block storage to send it an Acknowledge call before starting the consensus in order to avoid a race that can lead to high views.

there is no state in the genesis block, the virtual chain basic data will be set in the VC registration contract.

Closing the issue.
