### ISSUE TITLE
logger performance around strings

### ISSUE THREAD

**Issue by jlevison** [orbs-network/orbs-network-go#777]
logger right now is creating a lot of allocations in the way its built specifically:

* logFields() - uses a map which allocates on each assignment, maybe refactor to something else (which may even take more memory in absolute, but perform less allocations)
* func (j *jsonFormatter) FormatRow() - related to logFields, while jsonMarshal might be a necessity, try to work around using that map which is extremely expensive, also perhaps look into an alternative json encoder

**Comment by itamararjuan** [comment]
hey @jlevison  I'm thinking of changing the implementation of `logFields()` to loop over the fields and construct a string which represents all the variables in 1 swoop. and then inserting it into the `logLine` under a singular key called `params`. Will that solve some of the allocations in your opinion? I'm not an expert on allocations or the imeplementation details of Golang so I'm asking to be sure what I want to do will allow to save allocation operations.

**Comment by itamararjuan** [comment]
In terms of format row: I assume we can make the logger a bit more structured and instead of using a "flexible" map use a `struct` which covers most of the usecases we currently have so that the memory usage is optimized and not forcing the usage of marshalling, for example making sure we print out the json format in a different, more simple way , simply concatenating the already known fields (did I say struct yet?)  will that circumvent the memory consumption you are trying to avoid with using the maps? 
@jlevison

**Comment by itamararjuan** [comment]
@electricmonk if you can give some insight into what I'm purposing that would be lovely.

**Comment by electricmonk** [comment]
I think that this task isn't really interesting right now, but if you really want to work on it, I'd look on two thinks:
1) `strings.Builder`: https://www.calhoun.io/concatenating-and-building-strings-in-go/
2) look for a similar approach for streaming directly to json, so that we skip the two-phase process of first converting all log fields to a map and then marshalling the map as JSON, instead iterating all fields and directly marshalling them to JSON. A quick google search found this: https://github.com/francoispqt/gojay

**Comment by electricmonk** [comment]
fixed by @itamararjuan in https://github.com/orbs-network/scribe/pull/5
