### ISSUE TITLE
TestDirectOutgoing_AdapterSendsUnicast - is flaky

### ISSUE THREAD

**Issue by electricmonk** [orbs-network/orbs-network-go#973]
https://circleci.com/gh/orbs-network/orbs-network-go/11616
```
Error Trace:	direct_outgoing_test.go:81
            				context.go:11
            				direct_outgoing_test.go:66
Error:      	Not equal: 
            	expected: []byte{0x2, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0, 0x0, 0x11, 0x0, 0x0, 0x0, 0x2, 0x0, 0x0, 0x0, 0x22, 0x33, 0x0, 0x0}
            	actual  : []byte{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}
            	
            	Diff:
            	--- Expected
            	+++ Actual
            	@@ -1,4 +1,4 @@
            	 ([]uint8) (len=20) {
            	- 00000000  02 00 00 00 01 00 00 00  11 00 00 00 02 00 00 00  |................|
            	- 00000010  22 33 00 00                                       |"3..|
            	+ 00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
            	+ 00000010  00 00 00 00                                       |....|
            	 }
Test:       	TestDirectOutgoing_AdapterSendsUnicast
```

**Comment by ronnno** [comment]
the issue here is likely a timeout on the connection.

Found a mixup between network timeout and keepAliveInterval in `service_factory_presets.ForDirectTransportTests():22-23` 

additionally, it seems that at the time both values were 20ms which seems a little low for TCP under load. since then we have upgraded the testing machines.

additionally, a timeout should have been reflected in an error and not in an empty response.

still investigating

**Comment by ronnno** [comment]
another incident:
https://circleci.com/gh/orbs-network/orbs-network-go/14182?utm_campaign=chatroom-integration&utm_medium=referral&utm_source=slack

**Comment by ronnno** [comment]
Still looking into why when running some tests with hight `-count` the tests stall (as if read timeout does not apply).

Another concern is that in `TestDirectOutgoing_ErrorDuringSendCausesReconnect` I notice the outgoing queue becomes enabled before `Accept()` is called.

**Comment by ronnno** [comment]
Fix 4: Race condition in Client vs Server loops
After Fix 1 the clientLoop hangs if Dial() is called just before Accept(), when the keep alive interval is set to high values. This is an expected race condition, and is not a problem in production. This is cause by an improper use of keepAliveInterval. It is also used to sleep before attempting to reconnect if a problem is encountered and the connection is recycled. since keepAliveInterval in some tests is 20 hours, we don't recover from this race condition - where the client loop runs just before the server loop for the first iteration.

Fixed by adding a new config variable: GOSSIP_RECONNECT_INTERVAL which is simple never set too high.
